# Generated by Django 5.0.3 on 2024-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('movie', models.CharField(max_length=10)),
                ('multiplex', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seat', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('F', 'Front'), ('Mid', 'Middle'), ('BAL', 'Balcony')], max_length=5)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
