# Generated by Django 5.0.3 on 2024-03-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieticket',
            old_name='seat',
            new_name='no_seat',
        ),
    ]
